name: Coding Standard

on:
    pull_request: null
    push:
        branches:
            - "main"

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    coding_standard:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [8.1]
        steps:
            -   uses: actions/checkout@v4


            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php-versions }}"
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # see https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v3"

            -   run: composer fix-style

            -   uses: stefanzweifel/git-auto-commit-action@v5.0.0
                with:
                    commit_message: Apply coding standard changes
                    branch: "main"
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
